#===================================================================================
# https://github.com/ccccmagicboy/MicroPython_fw_action
# Description: Build MicroPython firmware using GitHub Actions for PYBV11
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: mpy-cross_win_BUILD

on:
  push:
    branches:
      - master
  # schedule:
    # - cron: 0 8 * * 5
  # watch:
    # types: [started]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2    

    - name: Clone the micropython source code
      run: git clone --depth 1 https://github.com/micropython/micropython.git -b master my_micropython

    - name: Get the python3
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'      

    - name: check python version
      run: |
        python -c "import sys; print(sys.version)"
        cd C:\hostedtoolcache\windows\Python\3.8.1\X64
        dir
        cp python.exe python3.exe
        dir
        python3 -c "import sys; print(sys.version)"
        
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MSYS

    - name: Make the mpy-cross
      run: |        
        cd my_micropython
        make -C mpy-cross