#===================================================================================
# https://github.com/ccccmagicboy/MicroPython_fw_action
# Description: Build MicroPython firmware using GitHub Actions for PYBV11
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: mpy-cross_win_BUILD

on:
  push:
    branches:
      - master
  # schedule:
    # - cron: 0 8 * * 5
  # watch:
    # types: [started]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2    

    - name: Clone the micropython source code
      run: git clone --depth 1 https://github.com/micropython/micropython.git -b master my_micropython

    - name: down the toolchain
      run: |
        curl -o toolchain.zip https://dl.espressif.com/dl/esp32_win32_msys2_environment_and_toolchain-20180110.zip
        7z x toolchain.zip
        ll