#===================================================================================
# https://github.com/ccccmagicboy/MicroPython_fw_action
# Description: Build MicroPython(LoBo) firmware using GitHub Actions for ESP32
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: ESP32_LoBo_BUILD

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build_for_ESP32_LoBo.yml'
    - '!**.md'
  schedule:
    - cron: 0 8 * * *
  # watch:
    # types: [started]
  
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │                                   
# │ │ │ │ │
# │ │ │ │ │
# * * * * *  

env:
  REPO_URL: https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo.git
  REPO_BRANCH: master
  TZ: Asia/Shanghai
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2
      
    - name: Install dependence
      run: |
        sudo apt-get install make unrar-free autoconf automake libtool gcc g++ gperf \
        flex bison texinfo gawk ncurses-dev libexpat-dev python-dev sed git unzip \
        bash help2man wget bzip2 libtool-bin python-serial

    - name: Clone the micropython source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH my_micropython
        
    - name: Take the sdkconfig
      working-directory: ./
      run: |
        echo 0
        
    - name: Take the partitions_mpy
      working-directory: ./
      run: |
        echo 0        

    - name: Build the source
      working-directory: ./my_micropython/MicroPython_BUILD
      run: |
        ./BUILD.sh -v
        cd build
        ls -al *.bin
        cd bootloader
        ls -al *.bin
        
    - name: Pack the bin files
      working-directory: ./my_micropython/MicroPython_BUILD/build
      run: |
        python ../../../tools/makeimg.py ./bootloader/bootloader.bin partitions_mpy.bin phy_init_data.bin MicroPython.bin firmware.bin
        ls -al
        
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Asia'
        tz2: 'Shanghai'        
        
    - name: Zip the artifact
      run: |
        zip --junk-paths LoBo_fw_${{ steps.get_datetime.outputs.datetime_str }} ./my_micropython/MicroPython_BUILD/build/firmware.bin README.md MicroPython_fw_action_card.png
        
    - name: Upload the zip file
      uses: actions/upload-artifact@master
      with:
        name: LoBo_fw_${{ steps.get_datetime.outputs.datetime_str }}
        path: LoBo_fw_${{ steps.get_datetime.outputs.datetime_str }}.zip        
        

