#===================================================================================
# https://github.com/ccccmagicboy/MicroPython_fw_action
# Description: Build MicroPython firmware using GitHub Actions for ESP32
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: ESP32_BUILD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
    - '**.md'      
  schedule:
    - cron: 0 8 * * 5
  # watch:
    # types: [started]

env:
  REPO_URL: https://github.com/micropython/micropython.git
  REPO_BRANCH: master
  TOOLCHAIN_FROM_SCRATCH: false
  TZ: Asia/Shanghai
  DIY_MPY_MODULES: true
  DIY_C_MODULES: true
  BOARD: GENERIC
  IDF_VERSION_V3: true
  IDF_VERSION_V4: true
  
jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2    
      
    - name: Get the python3
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'      

    - name: Install require for toolchain
      run: |
        sudo apt-get install gcc git wget make libncurses-dev flex \
        bison gperf python python-pip python-setuptools \
        python-cryptography python-future
        pip --version
        pip3 --version
        pip3 install --upgrade pip
        pip3 install pyserial 'pyparsing<2.4'
        
    - name: Down and install the toolchain
      if: env.TOOLCHAIN_FROM_SCRATCH == 'false'
      run: |
        mkdir -p my_toolchain
        cd my_toolchain
        curl -O https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        tar -xzf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        rm xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        export PATH=/home/runner/work/MicroPython_fw_action/MicroPython_fw_action/my_toolchain/xtensa-esp32-elf/bin:$PATH
        xtensa-esp32-elf-gcc --version
        
    - name: Clone the micropython source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH my_micropython
        git submodule update --init
        
    - name: Build the mpy-cross tool
      run: |
        cd my_micropython
        pwd
        ls -al
        make -C mpy-cross
        
    - name: Build the unix port
      run: |
        cd my_micropython/ports/unix
        make submodules
        make
        find . -name "*micropython*"
        ./micropython -c "import sys;print(sys.implementation)"

    - name: Get the IDF git hash of the only version(two of them)
      id: get_hash
      uses: ccccmagicboy/FW_esp32_get_IDF_hash_action@master
      with: 
        test: hahahaaaaa
        
    - name: Print the hashs
      run: |
        echo ${{ steps.get_hash.outputs.test_out }} 
        echo ${{ steps.get_hash.outputs.hash_v3 }} 
        echo ${{ steps.get_hash.outputs.hash_v4 }} 
        
    - name: Download the IDF v3 from espressif and make the esp32 port
      if: env.IDF_VERSION_V3 == 'true'
      run: |
        git clone https://github.com/espressif/esp-idf.git esp-idf_v3
        cd esp-idf_v3
        git checkout ${{ steps.get_hash.outputs.hash_v3 }}
        git submodule update --init --recursive
        cd ..
        ls -l
        cd esp-idf_v3
        pwd
        export ESPIDF=/home/runner/work/MicroPython_fw_action/MicroPython_fw_action/esp-idf_v3
        export PATH=/home/runner/work/MicroPython_fw_action/MicroPython_fw_action/my_toolchain/xtensa-esp32-elf/bin:$PATH
        xtensa-esp32-elf-gcc --version        
        cd ../my_micropython/ports/esp32
        make clean
        make submodules
        make

    - name: Zip the v3 artifact
      if: env.IDF_VERSION_V3 == 'true'
      run: |
        zip --junk-paths firmware_ESP32_IDF3_$BOARD my_micropython/ports/esp32/build-$BOARD/firmware.bin README.md MicroPython_fw_action_card.png
        
    - name: Upload the V3 zip file
      if: env.IDF_VERSION_V3 == 'true'
      uses: actions/upload-artifact@master
      with:
        name: firmware_ESP32_IDF3_${{ env.BOARD }}
        path: firmware_ESP32_IDF3_${{ env.BOARD }}.zip        
        
    - name: Download the IDF v4 from espressif and make the esp32 port
      if: env.IDF_VERSION_V4 == 'true'
      run: |
        git clone https://github.com/espressif/esp-idf.git esp-idf_v4
        cd esp-idf_v4
        git checkout ${{ steps.get_hash.outputs.hash_v4 }}
        git submodule update --init --recursive
        cd ..
        ls -l
        cd esp-idf_v4
        pwd
        export ESPIDF=/home/runner/work/MicroPython_fw_action/MicroPython_fw_action/esp-idf_v4
        export PATH=/home/runner/work/MicroPython_fw_action/MicroPython_fw_action/my_toolchain/xtensa-esp32-elf/bin:$PATH
        xtensa-esp32-elf-gcc --version        
        cd ../my_micropython/ports/esp32
        make clean
        make submodules
        make

    - name: Zip the v4 artifact
      if: env.IDF_VERSION_V4 == 'true'
      run: |
        zip --junk-paths firmware_ESP32_IDF4_$BOARD my_micropython/ports/esp32/build-$BOARD/firmware.bin README.md MicroPython_fw_action_card.png
        
    - name: Upload the V4 zip file
      if: env.IDF_VERSION_V4 == 'true'
      uses: actions/upload-artifact@master
      with:
        name: firmware_ESP32_IDF4_${{ env.BOARD }}
        path: firmware_ESP32_IDF4_${{ env.BOARD }}.zip
        
        
        