#===================================================================================
# https://github.com/ccccmagicboy/MicroPython_fw_action
# Description: Build a UF2 format bootloader using GitHub Actions
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: UF2_BOOT_BUILD

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build_for_UF2_bootloader.yml'
    - '!**.md'
  schedule:
    - cron: 0 9 * * *
  # watch:
    # types: [started]
    
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │                                   
# │ │ │ │ │
# │ │ │ │ │
# * * * * *  

env:
  REPO_URL: https://github.com/mmoskal/uf2-stm32f
  REPO_BRANCH: master

jobs:
  build:
    name: Build for STM32
    runs-on: ubuntu-16.04

    strategy:
      max-parallel: 2
      matrix:
        test-board:
        - f401
        # - f412
        - feather_f405
        - stm32f407-discovery
    
    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2     
      
    - name: Install the depend
      run: |
        sudo apt-get install gcc-arm-none-eabi
      
    - name: Clone the micropython source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH my_uf2
   
    # - name: Debug the action
      # uses: p3terx/debugger-action@master  
   
    - name: Build UF2
      working-directory: ./my_uf2
      run: |
        make BOARD=${{ matrix.test-board }}
        ls ./build/${{ matrix.test-board }} -al
        
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Asia'
        tz2: 'Shanghai'        
                
    - name: Zip the artifact
      run: |
        zip --junk-paths ${{ matrix.test-board }}_uf2_${{ steps.get_datetime.outputs.datetime_str }} ./my_uf2/build/${{ matrix.test-board }}/bootloader.bin README.md MicroPython_fw_action_card.png        
        
    - name: Upload the zip file
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.test-board }}_uf2_${{ steps.get_datetime.outputs.datetime_str }}
        path: ${{ matrix.test-board }}_uf2_${{ steps.get_datetime.outputs.datetime_str }}.zip        
        
        
        