#===================================================================================
# https://github.com/ccccmagicboy/MicroPython_fw_action
# Description: Build MicroPython firmware using GitHub Actions for openmv
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: openmv_BUILD

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build_for_openmv.yml'
    - '!**.md'
    
  schedule:
    - cron: 0 11 * * *
  # watch:
    # types: [started]
    
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │                                   
# │ │ │ │ │
# │ │ │ │ │
# * * * * *    

env:
  REPO_URL: https://github.com/openmv/openmv.git
  REPO_BRANCH: master
  TZ: Asia/Shanghai
  USB_DETACHED_HEAD: false  

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    strategy:
      max-parallel: 2
      matrix:
        board:
        - OPENMV4
        - OPENMV4P
        tag:
        - master
        
    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2    
      
    - name: Clone the micropython source code
      run: |
        git clone --recursive $REPO_URL -b $REPO_BRANCH
       
    - name: Checkout
      working-directory: ./openmv
      if: env.USB_DETACHED_HEAD == 'true'
      run: |
        git checkout ${{ matrix.tag }}      
   
    - name: Get the cross-toolchain
      run: |
        sudo apt-get remove gcc-arm-none-eabi
        sudo apt-get autoremove
        sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
        sudo apt-get update
        sudo apt-get install gcc-arm-embedded
        sudo apt-get install libc6-i386
        sudo apt-get install python2.7 python-dev python-pip
        sudo apt-get install libusb-1.0-0 libusb-1.0-0-dev
        sudo apt-get install python-gtksourceview2
        sudo pip install numpy pyserial==2.7 pyusb==1.0.0b2 Pillow
        sudo apt-get install make
        
    - name: Build the mpy-cross tool
      working-directory: ./openmv/src/micropython/mpy-cross
      run: |
        make        
        
    - name: Build
      working-directory: ./openmv/src
      run: |
        make V=0 TARGET=${{ matrix.board }} all
        ls ./build/bin -al
                      
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Asia'
        tz2: 'Shanghai'
        
    - name: Zip the artifact
      run: |
        zip --junk-paths openmv_${{ matrix.board }}_${{ steps.get_datetime.outputs.datetime_str }} /openmv/src/build/bin/bootloader.dfu /openmv/src/build/bin/firmware.dfu /openmv/src/build/bin/openmv.dfu README.md MicroPython_fw_action_card.png
        
    - name: Upload the Zip file
      uses: actions/upload-artifact@master
      with:
        name: openmv_${{ matrix.board }}_${{ steps.get_datetime.outputs.datetime_str }}
        path: openmv_${{ matrix.board }}_${{ steps.get_datetime.outputs.datetime_str }}.zip
              
              
              