#===================================================================================
# https://github.com/ccccmagicboy/MicroPython_fw_action
# Description: Build MicroPython firmware using GitHub Actions for mpy-cross
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: mpy-cross_BUILD

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build_for_mpy-cross.yml'
    - '!**.md'
  schedule:
    - cron: 0 8 * * *
  # watch:
    # types: [started]
    
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │                                   
# │ │ │ │ │
# │ │ │ │ │
# * * * * *  

env:
  REPO_URL: https://github.com/micropython/micropython.git
  REPO_BRANCH: master
  TZ: Asia/Shanghai    

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    
    env:
      DIY_SCRIPT: ./tools/mpy_cross_win_tool.py

    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2    

    - name: Clone the micropython source code
      run: git clone --depth 1 %REPO_URL% -b %REPO_BRANCH% my_micropython
      shell: cmd

    - name: Get the python3
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'      

    - name: Check python version
      run: |
        python -c "import sys; print(sys.version)"
        cp %pythonLocation%\python.exe %pythonLocation%\python3.exe
        python3 -c "import sys; print(sys.version)"
      shell: cmd
      
    - name: Run the DIY customs
      run: |
        python %DIY_SCRIPT%
      shell: cmd
      
    - name: Make the mpy-cross
      working-directory: .\my_micropython
      run: |
        echo %PATH%
        make -C mpy-cross
      shell: cmd
      
    - name: Print the version of mpy-cross.exe
      working-directory: .\
      id: print_ver
      shell: cmd
      run: |
        python -c "import os;from tools.mpy_cross_win_tool import get_ver;command = 'echo ::set-output name=version::{0:s}'.format(get_ver());print(command);print(os.popen(command).read())"
        
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Asia'
        tz2: 'Shanghai'
      
    - name: Zip the artifact
      run: |
        7z a mpy-cross_x64_windows_${{ steps.print_ver.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip my_micropython/mpy-cross/mpy-cross.exe README.md MicroPython_fw_action_card.png
      shell: cmd
      
    - name: Upload the zip file
      uses: actions/upload-artifact@master
      with:
        name: mpy-cross_x64_windows_${{ steps.print_ver.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}
        path: mpy-cross_x64_windows_${{ steps.print_ver.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip
        
  build_1:
    name: Build MACOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2    
      
    - name: Get the python3
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'      

    - name: Clone the micropython source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH my_micropython
        git submodule update --init
        
    - name: Build the mpy-cross tool
      working-directory: ./my_micropython/mpy-cross
      run: |
        make 
        
    - name: Print the version of mpy-cross
      working-directory: ./
      id: print_ver
      run: |
        python -c "import os;from tools.mpy_cross_win_tool import get_ver;command = 'echo ::set-output name=version::{0:s}'.format(get_ver());print(command);print(os.popen(command).read())"
        
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Asia'
        tz2: 'Shanghai'
      
    - name: Zip the artifact
      run: |
        7z a mpy-cross_macos_catalina_${{ steps.print_ver.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip my_micropython/mpy-cross/mpy-cross.exe README.md MicroPython_fw_action_card.png
      
    - name: Upload the zip file
      uses: actions/upload-artifact@master
      with:
        name: mpy-cross_macos_catalina_${{ steps.print_ver.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}
        path: mpy-cross_macos_catalina_${{ steps.print_ver.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip
