#===================================================================================
# https://github.com/ccccmagicboy/MicroPython_fw_action
# Description: Build MicroPython firmware using GitHub Actions for PYBV11
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: PYBV11_BUILD

on:
  release:
    types: [published]
  push:
    branches:
      - master
  # schedule:
    # - cron: 0 8 * * 5
  # watch:
    # types: [started]

env:
  REPO_URL: https://github.com/micropython/micropython.git
  REPO_BRANCH: master
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2    

    - name: Clone the micropython source code
      #depth用于指定克隆深度，为1即表示只克隆最近一次commit.
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH my_micropython

    - name: get the cross-toolchain
      run: |
        sudo apt-get install gcc-arm-none-eabi
        sudo apt-get install gcc
      
    - name: build the mpy-cross tool
      run: |
        cd my_micropython
        pwd
        ls -al
        make -C mpy-cross

    - name: build the submodules
      run: |        
        cd my_micropython/ports/stm32/
        pwd
        ls -al
        make submodules
        
    - name: build the PYBV11 dfu file
      run: |        
        cd my_micropython/ports/stm32/
        pwd
        ls -al
        make BOARD=PYBV11
        
    - name: Upload firmware dfu file
      uses: actions/upload-artifact@master
      with:
        name: firmware_PYBV11
        path: my_micropython/ports/stm32/build-PYBV11/firmware.dfu
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: v1.0
        release_name: Release v1.0
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false
        
    - name: zip the artifact
      run: |
        zip --junk-paths firmware_PYBV11 my_micropython/ports/stm32/build-PYBV11/firmware.dfu README.md        
        
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./
        asset_name: firmware_PYBV11.zip
        asset_content_type: application/zip        