#===================================================================================
# https://github.com/ccccmagicboy/MicroPython_fw_action
# Description: Build MicroPython firmware using GitHub Actions for STM32
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: STM32_BUILD

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build_for_PYBV11.yml'
    - '!**.md'
  schedule:
    - cron: 0 8 * * *
  # watch:
    # types: [started]
    
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │                                   
# │ │ │ │ │
# │ │ │ │ │
# * * * * *    

env:
  REPO_URL: https://github.com/micropython/micropython.git
  REPO_BRANCH: master
  UPLOAD_FIRMWARE: true
  MAKE_A_RELEASE_DRAFT: false
  TZ: Asia/Shanghai
  CUSTOM_FACTORY_RESET: true
  CUSTOM_MPCONFIGPORT: true
  DIY_MPY_MODULES: true
  DIY_C_MODULES: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04

    strategy:
      max-parallel: 1
      matrix:
        test-board:
        - PYBV11
        - PYBLITEV10
        - PYBV10
    
    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2    

    - name: Clone the micropython source code
      #depth用于指定克隆深度，为1即表示只克隆最近一次commit.
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH my_micropython
      
    - name: Clone the ulab
      run: |
        git clone https://github.com/v923z/micropython-ulab.git ulab

    - name: get the cross-toolchain
      run: |
        sudo apt-get install gcc-arm-none-eabi
        sudo apt-get install gcc
        pip3 --version        
        pip3 install --upgrade pip
        pip3 install pyelftools
      
    - name: build the mpy-cross tool
      run: |
        cd my_micropython
        pwd
        ls -al
        make -C mpy-cross
        
    - name: Build the unix port
      id: unix_port
      run: |
        cd my_micropython/ports/unix
        make submodules
        make
        find . -name "*micropython*"
        MOREF=$(./micropython -c "import sys;print('v{0:d}_{1:d}'.format(sys.implementation[1][0], sys.implementation[1][1]))")
        echo $MOREF
        echo "::set-output name=version::$MOREF"
        echo "::set-output name=board::${{ matrix.test-board }}"
        
    - name: Print the version
      run: |
        echo ${{ steps.unix_port.outputs.version }}
        
    - name: Build the submodules of stm32 port
      working-directory: ./my_micropython/ports/stm32
      run: |      
        make submodules
        
    - name: Custom the factoryreset.c file
      if: env.CUSTOM_FACTORY_RESET == 'true'
      run: echo "0"
      #uses: ccccmagicboy/FW_stm32_custom_factory_reset_action@master
      
    - name: Custom the mpconfigport.h file
      if: env.CUSTOM_MPCONFIGPORT == 'true'
      working-directory: ./my_micropython/ports/stm32/
      run: |
        echo "#define MODULE_ULAB_ENABLED (1)" >> mpconfigport.h
                
    - name: DIY micropython modules
      working-directory: ./my_micropython/ports/stm32/boards
      if: env.DIY_MPY_MODULES == 'true'
      run: |
        echo "freeze('\$(MPY_DIR)/../modules/STM32')" >> manifest.py
        echo "freeze('\$(MPY_DIR)/../modules/Universal')" >> manifest.py
        echo "freeze('\$(PORT_DIR)/modules')" >> manifest.py
        
    - name: upip micropython modules from internet
      working-directory: ./my_micropython/ports/unix
      run: |
        ./micropython -m upip install -p ../stm32/modules micropython-pystone_lowmem

    - name: DIY c mpy modules
      if: env.DIY_C_MODULES == 'true'
      working-directory: ./c_modules/
      run: |
        cd ./Universal/factorial
        make ARCH=armv7emsp
        ls -al
        
    - name: Upload c mpy file
      if: env.DIY_C_MODULES == 'true'
      uses: actions/upload-artifact@master
      with:
        name: factorial
        path: c_modules/Universal/factorial/factorial.mpy
        
    - name: Build the dfu file - ${{ matrix.test-board }}
      working-directory: ./my_micropython/ports/stm32/
      run: |
        make BOARD=${{ matrix.test-board }} USER_C_MODULES=../../../ulab MICROPY_PY_WIZNET5K=W5500 all
        
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Asia'
        tz2: 'Shanghai'            
        
    - name: Zip the artifact
      run: |
        zip --junk-paths ${{ steps.unix_port.outputs.board }}_fw_${{ steps.unix_port.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }} my_micropython/ports/stm32/build-${{ matrix.test-board }}/firmware.dfu README.md MicroPython_fw_action_card.png

    - name: Upload Zip file
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.unix_port.outputs.board }}_fw_${{ steps.unix_port.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip
        path: ${{ steps.unix_port.outputs.board }}_fw_${{ steps.unix_port.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip
        
    - name: Create Release
      if: env.MAKE_A_RELEASE_DRAFT == 'true'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: v1.0
        release_name: v1.0
        body: |
          Changes in this Release
          - First Change
          - Second Change
          - XXX
        draft: true
        prerelease: false
        
    - name: Upload Release Asset
      if: env.MAKE_A_RELEASE_DRAFT == 'true'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./${{ steps.unix_port.outputs.board }}_fw_${{ steps.unix_port.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip
        asset_name: ${{ steps.unix_port.outputs.board }}_fw_${{ steps.unix_port.outputs.version }}_${{ steps.get_datetime.outputs.datetime_str }}.zip
        asset_content_type: application/zip     

  build_1:
    name: Test
    needs: [build]
    runs-on: ubuntu-16.04
    steps:
    - name: hello
      run: |
        echo "hello"